# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pRlBjt8ARtd9kVJdvmu04dwCk5pA9-vB
"""

!pip install ultralytics roboflow

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="zDKfKvmEeTTVNkBFB9n8")
project = rf.workspace("roboflow-100").project("vehicles-q0x2v")
version = project.version(2)
dataset = version.download("yolov8")

from ultralytics import YOLO
model = YOLO('yolo11s.pt')
model.train(
    data=f"{dataset.location}/data.yaml",
    epochs=30,
    imgsz=640,
    plots=True
)

from PIL import Image
from IPython.display import display


metrics = model.val(split='test')
print(f"\n---> Итоговый mAP@50: {metrics.box.map50:.4f} <---")


my_photos = ['cars.jpeg', 'probka.jpg']

for file_path in my_photos:
    print(f"\n--- Обработка файла: {file_path} ---")


    results = model.predict(source=file_path, conf=0.15)

    for r in results:
        im_array = r.plot()
        im = Image.fromarray(im_array[..., ::-1])

        save_name = f'result_{file_path}'
        im.save(save_name)


        display(im)